### ISSUE TITLE
How to deploy kctf-operator 

### ISSUE THREAD

**Issue by apogiatzis** [google/kctf#356] opened 2022-02-03 00:48 UTC
Hey guys,

I was looking for instructions on how to build and deploy the kctf-operator and stumbled across this documentation page https://github.com/google/kctf/blob/v1/docs/kctf-operator.md however it seems that it's out of date.

Even though the instructions recommend using operator-sdk v0.18.x, when I try to generate the CRDs I am getting the following error:

```FATA[0000] failed to read config: error unmarshalling project configuration: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field Config.layout of type string```

Can you please advise on the matter?

**Comment by sroettger** [comment] 2022-02-03 08:27
Ah, Eduardo just updated the operator to a newer version I think. @sirdarckcat can you take a look?

**Comment by sirdarckcat** [comment] 2022-02-03 20:15
Oh, sorry, I forgot about that document

Here's the script we used, it can be ran after you activate kCTF.

https://github.com/google/kctf/blob/v1/kctf-operator/build-and-deploy-operator.sh

**Comment by sirdarckcat** [comment] 2022-02-03 20:16
Also this https://github.com/google/kctf/blob/v1/.github/workflows/update-images.yaml#L178 explains what to install

**Comment by apogiatzis** [comment] 2022-02-03 21:46
Thanks for the pointers! It's much appeciated!

However I am looking into deploying the operator on a kubernetes cluster on premise. So I assume the `${KCTF_BIN}/kctf-cluster" start` command would deploy the operator on a GKE cluster right? How would you suggest deploying the operator on an on premise cluster?

**Comment by sirdarckcat** [comment] 2022-02-03 21:54
hmm, well, some things wont work, but try it! add a namespace called `kctf-system` and then run `kubectl apply -f https://raw.githubusercontent.com/google/kctf/v1/dist/resources/operator.yaml`

that said, it's probably better for you to just send a pull request and modify the [`kind`](https://github.com/google/kctf/blob/v1/dist/bin/kctf-cluster#L699) cluster.

**Comment by apogiatzis** [comment] 2022-02-03 22:02
Will try it out! Thanks!

Also mentioning this here #342 as it seems related. 

I will keep you informed of the progress here.

**Comment by sirdarckcat** [comment] 2022-04-20 11:15
yep, I agree. I think we can mark this as a duplicate of 342.

**Closed as completed by sirdarckcat** 2022-04-20 11:15 UTC
